config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resource :search, only: [:new, :show]
  resources :tickets, except: [:edit]
 
  namespace :admin do
    resources :trains do
      resources :cars, shallow: true
    end
    resources :railway_stations do
      patch :set_number, on: :member
      patch :update_arrival_time, on: :member
      patch :update_departure_time, on: :member
    end
    resources :routes
    resources :tickets
    resources :users
    resources :cars
  end

  get 'welcome/index'

  root 'searches#show'
  

end

app/models/route.rb
class Route < ActiveRecord::Base

  
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains

  before_validation :set_name

  validates :name, presence: true
  validate :stations_count

  private

  def set_name
    self.name = "#{railway_stations.first.title} - #{railway_stations.last.title}"
  end

  def stations_count
    if railway_stations.size < 2
      errors.add(:base, "Route should contain at least 2 stations")
    end
  end
  
end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
  before_action :set_route, only: [:show, :edit, :update, :destroy]
  
  def index
    @routes= Route.all
  end

  def show    
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to [:admin, @route]
    else
      render :new
    end
  end

  def edit    
  end

  def update    
    if @route.update(route_params)
      redirect_to admin_routes_path
    else
      render :new
    end
  end

  def destroy    
    @route.destroy
    redirect_to admin_routes_path
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit( :name, railway_station_ids: [] )     
  end

end

app/views/admin/routes/_form.html.erb
<% hidden = false unless local_assigns[:hidden] %>

<%= form_for [:admin, route], html: { style: "display: #{hidden ? 'none' : 'block'}" } do |f| %>

 
  <div class="field">
    <%= f.label :name, 'Маршрут' %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :train, 'Назначить маршрут поезду:' %><br>
    <%= f.collection_select :train_ids, Train.all, :id, :number %>
  </div>

   <div class="field">
    <%= f.label :railway_station_ids, 'Добавить станции в маршрут:' %>
    <%= f.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, { multiple: true } %>
  </div>


  <div class="actions">
    <%= f.submit "#{ route.new_record? ? 'Создать' : 'Изменить'}" %>
  </div>
<% end %>

app/views/admin/routes/_route.html.erb
<tr>
  <td>
     <div id="route_name_<%= route.id %>">
        <%= route.name %>
     </div>
    <%= render 'form', route: route, hidden: true %>
</td>
  <td><%= link_to 'Показать', [:admin, route] %></td>
  <td><%= link_to 'Редактировать', '', class: 'edit_route', data: { route_id: route.id } %></td>
  <td><%= link_to 'Удалить', [:admin, route], method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/admin/routes/edit.html.erb
<h1>Изменить маршрут</h1>

<%= render 'form' %>

<%= link_to 'Назад', admin_routes_path %>

app/views/admin/routes/index.html.erb
<h1>Список маршрутов</h1>

<table class="table table-striped table-hover" >
  <tbody>
    <%= render @routes %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить маршрут', new_admin_route_path %>

app/views/admin/routes/new.html.erb
<h1>Добавить новый маршрут</h1>

<%= render 'form', route: @route %>

<%= link_to 'Назад', admin_routes_path %>

app/views/admin/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Маршрут</strong><br>
  <%= @route.name %>
</p>

<p>
  <% if @route.trains.empty? %>
      <p> Поездов на маршруте нет </p>
  <% else %>        
      <strong> Поезда на мрашруте: </strong> 
      <ul>  
      <% @route.trains.each do |train| %>        
        <li><%= train.number %></li>
      <% end %>
      </ul>
  <% end %>  
</p> 

<p>
  <% if @route.railway_stations.empty? %>
      <%= 'Cтанций в маршруте нет' %>
  <% else %>
    <strong>Список станций:</strong>
    <table>
      <thead>
        <tr>
          <td width = "100px"> Название </td>
          <td width = "150px"> Позиция </td>
          <td width = "200px"> Время прибытия </td>
          <td width = "200px"> Время отправления </td>
        </tr>
      </thead>
      <tbody>
      
        <% @route.railway_stations.ordered.each do |station| %>
        <tr>
        <td> <%= station.title %> </td>
        <td>  
          <%= form_tag set_number_admin_railway_station_path(station),  method: :patch do %>                   
            <%= hidden_field_tag(:route_id, @route.id) %>            
            <%= number_field_tag(:number, station.current_number(@route),
                                  id: "number_#{ station.title.parameterize.underscore }",
                                  min: 1,
                                  max: @route.railway_stations.size, step: 1) %>
            <%= submit_tag('Изменить') %>          
          <% end %>
        </td>
        <td>
              <%= form_tag update_arrival_time_admin_railway_station_path(station), method: :patch do %>
                <%= time_field_tag :arrival_time, station.arrival(@route).try(:strftime, "%H:%M") %>
                <%= hidden_field_tag :route_id, @route.id %>
                <%= submit_tag "Изменить" %>
              <% end %>
          </td>
          <td>
              <%= form_tag update_departure_time_admin_railway_station_path(station), method: :patch do %>
                <%= time_field_tag :departure_time, station.departure(@route).try(:strftime, "%H:%M") %>
                <%= hidden_field_tag :route_id, @route.id %>
                <%= submit_tag "Изменить" %>
              <% end %>
</td>
        </tr> 

        <% end %>    
      </tbody>    
    </table>
  <% end %>
</p>

<%= link_to 'Редактировать', edit_admin_route_path(@route) %> |
<%= link_to 'Назад', admin_routes_path %>