config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resource :search, only: [:new, :show]
  resources :tickets, except: [:edit]
 
  namespace :admin do
    resources :trains do
      resources :cars, shallow: true
    end
    resources :railway_stations do
      patch :set_number, on: :member
      patch :update_arrival_time, on: :member
      patch :update_departure_time, on: :member
    end
    resources :routes
    resources :tickets
    resources :users
    resources :cars
  end

  get 'welcome/index'

  root 'searches#show'
  

end

app/models/car.rb
class Car < ActiveRecord::Base
  

  belongs_to :train

  validates :number,   presence: true
  validates :number, uniqueness: { scope: :train_id }
  scope :coupe, -> { where(type: "CoupeCar") }
  scope :economy, -> { where(type: "EconomyCar") }
  scope :comfort, -> { where(type: "ComfortCar") }
  scope :seat, -> { where(type: "SeatCar") }
  scope :ordered, -> (from_head) { order(from_head ? 'number' : 'number DESC')}

  before_validation :set_number
  
  private
  
  def set_number
    number = self.train.cars.maximum(:number)
    self.number = number.nil? ? 1 : number + 1
  end

end

app/controllers/admin/cars_controller.rb
class Admin::CarsController < Admin::BaseController
  before_action :set_train, only: [:new, :create]
  
  def index
    
  end

  def show  
    @car = Car.find(params[:id])  
  end

  def new    
    @car = Car.new
  end

  def create
    @car = @train.cars.new(car_params)

    if @car.save
      redirect_to [:admin, @train]
    else
      render :new
    end
  end

  def edit    
  end

  def update    
    
  end

  def destroy    
   
  end

  protected

  def set_train
    @train = Train.find(params[:train_id])
  end

  def car_params
    params.require(:car).permit(:number, :top_places, :bottom_places, :side_top_places, 
      :side_bottom_places, :seat_places, :train_id, :type)    
  end

end

app/views/admin/cars/_car.html.erb
<tr> <br>

  <% if @car.type == "EconomyCar" %> 
      <td> Плацкарт </td><br>
      <td>Количество верхних мест <%= "#{@car.top_places}" %> <br>
      <td>Количество нижних мест <%= "#{@car.bottom_places}" %> <br>
      <td>Количество боковых верхних мест <%= "#{@car.side_top_places}" %> <br>
      <td>Количество боковых нижних мест <%= "#{@car.side_bottom_places}" %> <br>
      <% elsif @car.type == "CoupeCar" %> 
        <td>Купе <br>
        <td>Количество верхних мест <%= "#{@car.top_places}" %> <br>
        <td>Количество нижних мест <%= "#{@car.bottom_places}" %>   <br>   
      <% elsif @car.type == "ComfortCar" %> 
        <td>СВ-вагон<br>
        <td>Количество нижних мест <%= "#{@car.bottom_places}" %> <br>
      <% elsif @car.type == "SeatCar" %> 
        <td>Сидячий вагон<br>
        <td>Количество мест <%= "#{@car.seat_places}" %> <br>
      <% end %>   
</tr>

app/views/admin/cars/_form.html.erb
<%= form_for [:admin, @train, @car] do |f| %>

<%= render 'common/errors', resource: @car %>
 
  <div class="field">
    <%= f.label :type, "Купе" %>
    <%= f.radio_button :type, "CoupeCar" %>
  </div>

  <div class="field">
    <%= f.label :type, "Плацкарт" %>
    <%= f.radio_button :type, "EconomyCar" %>
  </div>
  
  <div class="field">
    <%= f.label :type, "СВ" %>
    <%= f.radio_button :type, "ComfortCar" %>
  </div>
  
  <div class="field">
    <%= f.label :type, "Сидячий вагон" %>
    <%= f.radio_button :type, "SeatCar" %>
  </div>
 
  <div class="field">
    <%= f.label :top_places, 'Количество верхних мест' %><br>
    <%= f.number_field :top_places, min: 0, max: 60 %><br>
  </div>
  
  <div class="field">
    <%= f.label :bottom_places, 'Количество нижних мест' %><br>
    <%= f.number_field :bottom_places, min: 0, max: 60  %><br>
  </div>  
  
  <div class="field">
    <%= f.label :side_top_places, 'Количество боковых верхних мест' %><br>
    <%= f.number_field :side_top_places, min: 0, max: 60 %><br>
  </div> 
  
  <div class="field">
    <%= f.label :side_bottom_places, 'Количество боковых нижних мест' %><br>
    <%= f.number_field :side_bottom_places, min: 0, max: 60 %><br>
  </div>
  
  <div class="field">
    <%= f.label :seat_places, 'Количество сидячих мест' %><br>
    <%= f.number_field :seat_places, min: 0, max: 60  %><br>
  </div> 
  
  <div class="field">
    <%= f.label :numbeacr, 'номер' %><br>
    <%= f.text_field :number %>
  </div> 

  

  <div class="actions">
   <%= f.submit "#{ @car.new_record? ? 'Создать' : 'Изменить'}" %>
  </div>
<% end %>

app/views/admin/cars/edit.html.erb
<h1>Изменить вагон</h1>

<%= render 'form' %>

<%= link_to 'Назад', admin_cars_path %>

app/views/admin/cars/index.html.erb
<h1>Список вагонов</h1>



<table>
  <thead>
    <tr>
      <th>Вагон:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% @cars.each do |car| %>
    <tr>
    <td> <%= car.type %> <td>
    <td> <%= car.number %> <td>
    <td><%= link_to 'Показать', [:admin, car.becomes(Car)] %></td>
    <td><%= link_to 'Редактировать', edit_admin_car_path(car) %></td>
    <td><%= link_to 'Удалить', [:admin, car.becomes(Car)], method: :delete, data: { confirm: 'Вы уверены?' } %></td>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить вагон', new_admin_car_path %>

app/views/admin/cars/new.html.erb
<h1>Добавить новый вагон</h1>

<%= render 'form' %>

<%= link_to 'Назад', @car.train %>

app/views/admin/cars/show.html.erb
<p>
  <strong>Вагон</strong>
  <%= render 'car' %>  
</p>
 


<%= link_to 'Назад', [:admin, @car.train] %>