config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resource :search, only: [:new, :show]
  resources :tickets, except: [:edit]
 
  namespace :admin do
    resources :trains do
      resources :cars, shallow: true
    end
    resources :railway_stations do
      patch :set_number, on: :member
      patch :update_arrival_time, on: :member
      patch :update_departure_time, on: :member
    end
    resources :routes
    resources :tickets
    resources :users
    resources :cars
  end

  get 'welcome/index'

  root 'searches#show'
  

end

app/models/train.rb
class Train < ActiveRecord::Base

  
  belongs_to :route
  has_many :tickets
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  has_many :cars

  validates :number, presence: true
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  # GET /trains
  # GET /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1
  # GET /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  # POST /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to [:admin, @train], notice: 'Train was successfully created.' }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to admin_trains_path, notice: 'Train was successfully updated.' }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to trains_url, notice: 'Train was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:number, :route_id, :sort_from_head)
    end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  # GET /trains
  # GET /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1
  # GET /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  # POST /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to @train, notice: 'Train was successfully created.' }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to @train, notice: 'Train was successfully updated.' }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to trains_url, notice: 'Train was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:number, :route_id, :sort_from_head)
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/admin/trains/_form.html.erb
<% hidden = false unless local_assigns[:hidden] %>

<%= form_for [:admin, train], html: { style: "display: #{hidden ? 'none' : 'block'}" } do |f| %>


  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  
   <div class="field">
    <%= f.label t('.num_of_head') %><br>
    <%= f.check_box :sort_from_head %>
  </div>

  <div class="actions">    
    <%= f.submit t('common.edit')%>
  </div>

  <div class="field">
    <%= f.label :route, t('.route') %><br>
    <%= f.collection_select :route_id, Route.all, :id, :name %>
  </div>

  <div class="actions">    
    <%= f.submit t('.submit', action: train.new_record? ? t('common.new') : t('common.edit')) %>
  </div>
<% end %>

app/views/admin/trains/_train.html.erb
<tr>
   <td>
    <div id="train_number_<%= train.id %>">
      <%= train.number %>
    </div>
    <%= render 'form', train: train, hidden: true %>
  </td>
  <td><%= link_to t('common.show'), [:admin, train] %></td>
  <td><%= link_to t('common.edit'), '', class: 'edit_train', data: { train_id: train.id } %></td>
  <td><%= link_to t('common.destroy'), [:admin, train], method: :delete, data: { confirm: t('common.confirm') } %></td>
</tr>

app/views/admin/trains/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', train:  @train %>

<%= link_to t('common.show'), [:admin, @train] %> |
<%= link_to t('common.back'),  admin_trains_path %>

app/views/admin/trains/index.html.erb
<h1><%= t('.title') %></h1>


<table class="table table-striped table-hover" >

  <tbody>
    <%= render @trains %>    
  </tbody>
</table>

<br>

<%= link_to t('.new'), new_admin_train_path %>

app/views/admin/trains/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', train: @train  %>

<%= link_to t('common.back'), admin_trains_path %>

app/views/admin/trains/show.html.erb
<p>
  <strong>Поезд номер:</strong>
  <%= @train.number %>
</p>

<p>
<% if @train.route.present? %>
    Назначен следующий маршрут:
    <%= @train.route.name %>    
<% else %>
    Маршрут не назначен     
<% end %>
</p>
<% if @train.sort_from_head %>
  <p> <b> Нумерация с головы </b> </p>
<% else %>
  <p> <b> Нумерация с хвоста </b> </p>
<% end %>

<%if @train.cars.empty? %>
  <p> Нет вагонов </p>
<% else %>
  <p>Вагоны </p>
  <% @train.cars.ordered(@train.sort_from_head).each  do |car| %>
    <ul>
      <%= link_to "Вагон №#{car.number}", [:admin, car.becomes(Car) ]%> 
    </ul>
  <% end %>
<% end %>

<p>
  <strong>В поезде:</strong>
  <ul>
    <ins> Плацкартных вагонов: 
    <%= @train.cars.economy.count %></ins>
     <li> Общее количество верхних полок:
    <%= @train.cars.economy.sum(:top_places) %></li>
    <li> Общее количество нижних полок::
    <%= @train.cars.economy.sum(:bottom_places) %></li>
    <li> Общее количество боковых верхних полок:
    <%= @train.cars.economy.sum(:side_top_places) %></li>
    <li> Общее количество боковых нижних полок::
    <%= @train.cars.economy.sum(:side_bottom_places) %></li>
    
    <ins>Купейных вагонов:
    <%= @train.cars.coupe.count %></ins>
     <li> Общее количество верхних полок:
    <%= @train.cars.coupe.sum(:top_places) %></li>
    <li> Общее количество нижних полок::
    <%= @train.cars.coupe.sum(:bottom_places) %></li>
   
    <ins>СВ-вагонов:
     <%= @train.cars.comfort.count %></ins>    
    <li> Общее количество нижних полок::
    <%= @train.cars.comfort.sum(:bottom_places) %></li>
       
    <ins>Сидячих вагонов:
    <%= @train.cars.seat.count %></ins>
    <li> Общее количество сидячих мест:
    <%= @train.cars.seat.sum(:seat_places) %></li>   
    </ul> 
</p>

<p>
<%= link_to t('common.new'), new_admin_train_car_path(@train) %> |
<%= link_to t('common.edit'), edit_admin_train_path(@train) %> |
<%= link_to t('common.destroy'), admin_trains_path %>