config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resource :search, only: [:new, :show]
  resources :tickets, except: [:edit]
 
  namespace :admin do
    resources :trains do
      resources :cars, shallow: true
    end
    resources :railway_stations do
      patch :set_number, on: :member
      patch :update_arrival_time, on: :member
      patch :update_departure_time, on: :member
    end
    resources :routes
    resources :tickets
    resources :users
    resources :cars
  end

  get 'welcome/index'

  root 'searches#show'
  

end

app/models/car.rb
class Car < ActiveRecord::Base
  

  belongs_to :train

  validates :number,   presence: true
  validates :number, uniqueness: { scope: :train_id }
  scope :coupe, -> { where(type: "CoupeCar") }
  scope :economy, -> { where(type: "EconomyCar") }
  scope :comfort, -> { where(type: "ComfortCar") }
  scope :seat, -> { where(type: "SeatCar") }
  scope :ordered, -> (from_head) { order(from_head ? 'number' : 'number DESC')}

  before_validation :set_number
  
  private
  
  def set_number
    number = self.train.cars.maximum(:number)
    self.number = number.nil? ? 1 : number + 1
  end

end

app/models/comfort_car.rb
class ComfortCar < Car

  validates :bottom_places, presence: true

end

app/models/coupe_car.rb
class CoupeCar < ComfortCar

  validates :top_places, presence: true

end

app/models/economy_car.rb
class EconomyCar < CoupeCar

  validates  :side_top_places, :side_bottom_places, presence: true

end

app/models/railway_station.rb
class RailwayStation < ActiveRecord::Base

  
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes
  has_many :trains, foreign_key: :railway_station_id


  validates :title, presence: true

  # scope :ordered, -> { joins(:railway_stations_routes).order('railway_stations_routes.number').uniq }
  scope :ordered, -> { joins(:railway_stations_routes).select('railway_stations_routes.*, railway_stations.title, railway_stations.id').order('railway_stations_routes.number').uniq }

  def update_number(route, number)
    station_route = station_route(route)
    station_route.update(number: number) if station_route
  end

  def current_number(route)
    station_route(route).try(:number)
  end

  def update_arrival_time(route, arrival_time)
    station_route = station_route(route)
    station_route.update(arrival_time: arrival_time) if station_route
  end

  def arrival(route)
    station_route(route).try(:arrival_time)
  end

  def update_departure_time(route, departure_time)
    station_route = station_route(route)
    station_route.update(departure_time: departure_time) if station_route
  end

  def departure(route)
    station_route(route).try(:departure_time)
  end

  protected

  def station_route(route)
    @station_route ||= railway_stations_routes.where(route: route).first
  end
end

app/models/railway_stations_route.rb
class RailwayStationsRoute< ActiveRecord::Base

  belongs_to :railway_station
  belongs_to :route

  validates :railway_station_id, uniqueness: { scope: :route_id }

  
end

app/models/route.rb
class Route < ActiveRecord::Base

  
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains

  before_validation :set_name

  validates :name, presence: true
  validate :stations_count

  private

  def set_name
    self.name = "#{railway_stations.first.title} - #{railway_stations.last.title}"
  end

  def stations_count
    if railway_stations.size < 2
      errors.add(:base, "Route should contain at least 2 stations")
    end
  end
  
end

app/models/search.rb
class Search < ActiveRecord::Base
  def self.get_trains(first_station, last_station)
    if first_station != last_station
      routes = Route.joins(:railway_stations).where(railway_stations: { id: first_station }) &
               Route.joins(:railway_stations).where(railway_stations: { id: last_station })
      Train.joins(:route).where(route: routes)
    end
  end
end

app/models/seat_car.rb
class SeatCar < Car

  validates :seat_places, presence: false

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base

  
  belongs_to :train
  belongs_to :first_station, class_name: 'RailwayStation', foreign_key: :first_station_id
  belongs_to :last_station, class_name: 'RailwayStation', foreign_key: :last_station_id
  belongs_to :user

  after_create :send_buy_notification
  after_destroy :send_cancel_notification

  validates :code, presence: true
  validates :full_name_user, presence: true

  def route_name
    "#{first_station.title} - #{last_station.title}"
  end

  private

  def send_buy_notification
    TicketsMailer.buy_ticket(self.user, self).deliver_now
  end

  def send_cancel_notification
    TicketsMailer.cancel_ticket(self.user, self).deliver_now
  end

end

app/models/train.rb
class Train < ActiveRecord::Base

  
  belongs_to :route
  has_many :tickets
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  has_many :cars

  validates :number, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
    
  has_many :tickets

  #validates :name, presence: true
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_stations, only: [:new, :show]
  def show
    
  end

  def new
    @trains = Search.get_trains(params[:from], params[:to])
    render :show
  end

  def create
    
  end

  private

  def set_stations
    @stations = RailwayStation.all
end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  
  def index
    @tickets= current_user.tickets
  end

  def show    
  end

  def new
    @ticket = Ticket.new
  end

  def create    
    @ticket = current_user.tickets.new(ticket_params)     

    if @ticket.save

      redirect_to @ticket
    else
      render :new
    end
  end

  def edit    
  end

  def update    
    if @ticket.update(ticket_params)
      redirect_to @ticket
    else
      render :new
    end
  end

  def destroy    
    @ticket.destroy
    redirect_to tickets_path
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end  

  def ticket_params
    params.require(:ticket).permit(:code, :full_name_user, :passport, :train_id, :user_id, :first_station_id, :last_station_id)    
  end

  
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  # GET /trains
  # GET /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1
  # GET /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  # POST /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to @train, notice: 'Train was successfully created.' }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to @train, notice: 'Train was successfully updated.' }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to trains_url, notice: 'Train was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:number, :route_id, :sort_from_head)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_errors.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2><%= t('common.errors') %></h2>
    <ul>
    <% resource.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tutu" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Tutu</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <% if current_user.admin? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Админка<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to t('common.stations'), admin_railway_stations_path %></li>
                    <li><%= link_to t('common.trains'), admin_trains_path %></li>
                    <li><%= link_to t('common.routes'), admin_routes_path %></li>
                    <li><%= link_to t('common.cars'), admin_cars_path %></li>
                    <li><%= link_to t('common.tickets'), admin_tickets_path %></li>
                  </ul>
                </li>
              <% end %>
              <li><%= link_to t('common.exit'), destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to t('common.login'), new_user_session_path  %></li>
              <li><%= link_to t('common.register'), new_user_registration_path %></li>
            <% end %>            
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
       
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        &copy 2016 Бояринцев Денис. Учебный проект в <%= link_to 'онлайн-школе Thinknetica.', 'http://www.thinknetica.com' %>
      </footer>

    </div> <!-- /container -->

  </body>
</html>